Poptraq/app.py
from flask import Flask, render_template, request, url_for
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, Manager, MigrateCommand
from form import Signup
from models import User

app = Flask(__name__)
app.config['SECRET_KEY'] = "$poptraq#"
app.config['SQLALCHEMY_DATABASE_URI'] = "postgresql://localhost/poptraq"
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)
manager = Manager(app)
manager.add_command('db', MigrateCommand)
migrate = Migrate(app, db)
Bootstrap(app)


@app.route('/')
def dash():
    return render_template("dash.html")


@app.route('/login')
def login():
    return render_template("login.html")


@app.route('/logout')
def logout():
    return "To configure"


@app.route('/signup')
def signup():
    form = Signup(request.form)  # instantiating form to use the forms defined from the Form class in form.py

    if request.method == 'GET':
        return render_template('signup.html', form=form)
    else:
        if not form.validate_on_submit():  # making sure that the form is validated before submission
            return render_template('signup.html', form=form, not_validate=True)
        else:
            User.__init__(national_id=request.form['national_id'],
                          first_name=request.form['first_name'],
                          surname=request.form['surname'],
                          dob=request.form['dob'],
                          home_county=request.form['home_county'],
                          email=request.form['email'],
                          password=request.form['password'])
            return url_for('account')


@app.route('/account/')
def account():
    return render_template("account.html")

poptraq/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, Manager, MigrateCommand
from flask_bootstrap import Bootstrap
from flask_debug import Debug
from flask_mail import Mail
from flask_recaptcha import ReCaptcha
from flask_socketio import SocketIO
import sentry_sdk
from sentry_sdk.integrations.flask import FlaskIntegration

sentry_sdk.init(
    dsn="https://9893fa47a103437785f3f1bb07f81835@sentry.io/1302450",
    integrations=[FlaskIntegration()],
    max_breadcrumbs=50,
    debug=True
)

app = Flask(__name__)
app.config.update(
    DEBUG=True,
    MAIL_SERVER='smtp.gmail.com',
    MAIL_PORT=465,
    MAIL_USE_SSL=True,
    MAIL_USERNAME='anyapp8@gmail.com',
    MAIL_PASSWORD='anyapp8#@123',
    MAIL_DEFAULT_SENDER = "anyapp8@gmail.com",

    RECAPTCHA_ENABLED=True,
    RECAPTCHA_PUBLIC_KEY="6LfgSHMUAAAAAPCT_9i_stHIR_AxowHyHvF-oD0z",
    RECAPTCHA_PRIVATE_KEY="6LfgSHMUAAAAAEhiNnOEep3jwRgATmKsdmjEpbl_",
    RECAPTCHA_THEME="dark",
    RECAPTCHA_TYPE="image",
    RECAPTCHA_SIZE="compact",
    RECAPTCHA_RTABINDEX=10,
    RECAPTCHA_PARAMETERS={'hl': 'en-GB'},

    SECRET_KEY="$poptraq#",
    SECURITY_PASSWORD_SALT="@tre3potraq#",
    # SQLALCHEMY_DATABASE_URI="postgres://unjltzspnbvjzb:e511c61dacd775cffc0857dde01511955532ef8b08c88c897b0d21b874f94848"
    #                         "@ec2-54-221-251-195.compute-1.amazonaws.com:5432/d1lqqk8qoqodln",
    SQLALCHEMY_DATABASE_URI="postgresql://postgres:postgres@localhost:5432/potraq",
    SQLALCHEMY_TRACK_MODIFICATIONS=False,
    BCRYPT_LOG_ROUNDS=13,
    WTF_CSRF_ENABLED=True

)

app.config.update(dict(
    RECAPTCHA_SITE_KEY="public",
    RECAPTCHA_SECRET_KEY="private",
))

recaptcha = ReCaptcha()
recaptcha.init_app(app)

login_manager = LoginManager(app)
login_manager.init_app(app)
login_manager.login_view = 'login'
login_manager.login_message = u"Login required to gain access"
login_manager.login_message_category = "info"

bootstrap = Bootstrap(app)

Debug(app)

mail = Mail(app)

db = SQLAlchemy(app)

socketio = SocketIO(app)


from poptraq.models import User, County
from poptraq import views
from poptraq.views import admin, user, views

manager = Manager(app)
manager.add_command('db', MigrateCommand)

migrate = Migrate(app, db)

poptraq/views/__init__.py
# Python package initialiser

poptraq/views/user.py
from datetime import datetime

import pytz
from flask import render_template, request, Blueprint, url_for, redirect, flash
from flask_login import current_user, login_user, logout_user, login_required
from sqlalchemy.exc import InternalError, ProgrammingError
from werkzeug.security import generate_password_hash, check_password_hash

from poptraq import app, db
from poptraq.decorators import confirmed, unconfirmed_user, anonymous, normal_user
from poptraq.email import send_email
from poptraq.form import RegistrationForm, EmailForm, PasswordForm, DetailsForm
from poptraq.models import User, Details
from poptraq.token import generate_confirmation_token, confirm_token

user = Blueprint('user', __name__, url_prefix='/user')


@user.route('/', methods=['GET'])
@login_required
@normal_user
@unconfirmed_user
def unconfirmed():
    return render_template('user/unconfirmed.html')


@user.route('/account', methods=['GET'])
@login_required
@normal_user
@confirmed
def account():
    return render_template('user/account.html')


@user.route('/register_user', methods=['GET', 'POST'])
@anonymous
def register():
    # Manage accounts using Activity Status
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(request.form['national_id'],
                        request.form['first_name'],
                        request.form['surname'],
                        request.form['dob'],
                        request.form['home_county'],
                        request.form['email'],
                        generate_password_hash(request.form['password'], method='pbkdf2:sha256', salt_length=8))
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user, remember=form.remember_me.data)
        send_confirm_link()
        return redirect(url_for('user.unconfirmed'))
    return render_template('app/register.html', form=form)


@user.route('/send_link', methods=['GET'])
@login_required
@normal_user
@unconfirmed_user
def send_confirm_link():
    new_user = User.query.filter_by(email=current_user.email).first_or_404()
    token = generate_confirmation_token(new_user.email)
    confirm_url = url_for('user.confirm_email', token=token, _external=True)
    name = new_user.first_name
    html = render_template('user/activate.html', confirm_url=confirm_url, name=name)
    subject = "Please confirm your email"
    send_email(new_user.email, subject, html)
    flash('Confirmation Email has been sent to: ' + current_user.email, category='success')
    return redirect(url_for('user.unconfirmed'))


@user.route('/confirm/<token>', methods=['GET'])
@login_required
@normal_user
@unconfirmed_user
def confirm_email(token):
    try:
        email = confirm_token(token)
        new_user = User.query.filter_by(email=email).first()
        if new_user.email != current_user.email:
            flash("Link Exists for another Account: " + current_user.email + ". Logout and Login with your account to "
                                                                             "confirm", category='danger')
            return redirect(url_for('user.account'))
        d = datetime.now()
        timezone = pytz.timezone("Africa/Nairobi")
        d_aware = timezone.localize(d)

        new_user.updated = d_aware.strftime("%B %d, %Y %H:%M:%S")
        new_user.confirmed = True
        new_user.confirmed_on = d_aware.strftime("%B %d, %Y %H:%M:%S")
        db.session.add(new_user)
        db.session.commit()
        flash('Successfully Confirmed your Account', category='success')
        return redirect(url_for('user.account'))
    except InternalError and ProgrammingError:
        if current_user.confirmed:
            flash('Your Account is already Confirmed', category='info')
            return redirect(url_for('user.account'))
        flash('Your Confirm Link is Expired, resend to confirm', category='danger')
        return render_template('user/unconfirmed.html')


@user.route('/reset', methods=["GET", "POST"])
def recover():
    if current_user.is_authenticated:
        flash('Already Logged in, Log out to Reset Password', category='warning')
        return redirect(url_for('user.account'))
    form = EmailForm()
    if form.validate_on_submit():
        token = generate_confirmation_token(form.email.data)
        confirm_url = url_for('user.reset', token=token, _external=True)
        html = render_template('user/reset.html', confirm_url=confirm_url)
        subject = "Password Reset"
        send_email(form.email.data, subject, html)
        return render_template('user/recover.html', show=True)
    return render_template('user/recover.html', form=form, reset=True)


@user.route('/reset/<token>', methods=['GET'])
def reset(token):
    if not current_user.is_authenticated:
        try:
            new_user = User.query.filter_by(email=confirm_token(token)).first()
            if new_user:
                flash('Fill in Form to Reset Password', category='success')
                form = PasswordForm()
                return render_template('recover.html', form=form, new=True)
            flash('Invalid Email, Try Again!', category='warning')
            return redirect(url_for('user.recover'))
        except InternalError and ProgrammingError:
            flash('Your Reset Link is Expired, Try Again', category='danger')
            return redirect(url_for('user.recover'))
    flash('You are Logged in, log out to Reset Password', category='warning')
    return redirect(url_for('user.account'))


@user.route('/password_reset', methods=['POST'])
@anonymous
def password_reset():
    form = PasswordForm()
    if form.validate_on_submit():
        new_user = User.query.filter_by(email=reset.email).first()
        if new_user:
            if not check_password_hash(new_user.password, form.password.data):
                d = datetime.now()
                timezone = pytz.timezone("Africa/Nairobi")
                d_aware = timezone.localize(d)

                new_user.updated = d_aware.strftime("%B %d, %Y %H:%M:%S")
                new_user.password = generate_password_hash(form.password.data,
                                                           method='pbkdf2:sha256', salt_length=8)
                db.session.add(new_user)
                db.session.commit()
                flash('Successfully Updated your Password', category='success')
                return redirect(url_for('login'))
            flash('That is your old Password, Reset Aborted', category='info')
            return redirect(url_for('login'))
        flash('Invalid Email, Try Again', category='warning')
        return redirect(url_for('user.recover'))
    return render_template('user/recover.html', form=form, new=True)


@user.route('/details', methods=['GET'])
@login_required
@normal_user
@confirmed
def details():
    form = DetailsForm()
    if form.validate_on_submit():
        detail = Details(request.form['passport_photo'],
                         request.form['age'],
                         request.form['gender'],
                         request.form['marital_status'],
                         request.form['specifics'])
        db.session.add(detail)
        db.session.commit()
        return redirect(url_for('user.account'))
    return render_template('user/details.html', form=form)


@user.route('/notifications', methods=['GET'])
@login_required
@normal_user
@confirmed
def notifications():
    pass


@user.route('/settings', methods=['GET'])
@login_required
@normal_user
@confirmed
def settings():
    pass


@user.route('/logout', methods=['GET'])
@login_required
@normal_user
def logout():
    logout_user()
    flash('Logout Successful', category='success')
    return redirect(url_for('index'))


app.register_blueprint(user)

poptraq/views/views.py
import os
from datetime import datetime

import markdown
import pytz
from flask import render_template, send_from_directory, Markup, flash, request, redirect, url_for
from flask_login import login_user, current_user
from werkzeug.security import check_password_hash

from poptraq import app, db
from poptraq.decorators import anonymous
from poptraq.form import LoginForm
from poptraq.models import User, County


@app.route('/', methods=['GET'])
def index():
    results = County.query.order_by(County.id)
    return render_template('app/index.html', results=results)


@app.route('/sources', methods=['GET'])
def sources():
    return render_template('app/sources.html')


@app.route('/login', methods=['GET', 'POST'])
@anonymous
def login():
    # Manage account login with active status
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(national_id=form.national_id.data, email=form.email.data).first()
        if user and check_password_hash(user.password, form.password.data):
            if user.status == 'Active':
                if user.admin and user.user:
                    login_user(user, remember=form.remember_me.data)

                    d = datetime.now()
                    timezone = pytz.timezone("Africa/Nairobi")
                    d_aware = timezone.localize(d)

                    user.last_seen = d_aware.strftime("%B %d, %Y %H:%M:%S")
                    db.session.add(user)
                    db.session.commit()

                    flash('Successful Login SuperAdmin: ' + current_user.email, category='success')
                    return redirect(url_for('admin.home'))
                elif user.admin:
                    login_user(user, remember=form.remember_me.data)

                    d = datetime.now()
                    timezone = pytz.timezone("Africa/Nairobi")
                    d_aware = timezone.localize(d)

                    user.last_seen = d_aware.strftime("%B %d, %Y %H:%M:%S")
                    db.session.add(user)
                    db.session.commit()

                    flash('Successful Login Admin: ' + current_user.email, category='success')
                    return redirect(url_for('admin.home'))
                elif user.user:
                    login_user(user, remember=form.remember_me.data)

                    d = datetime.now()
                    timezone = pytz.timezone("Africa/Nairobi")
                    d_aware = timezone.localize(d)

                    user.last_seen = d_aware.strftime("%B %d, %Y %H:%M:%S")
                    db.session.add(user)
                    db.session.commit()

                    flash('Successful Login User: ' + current_user.email, category='success')
                    return redirect(url_for('user.account'))
        flash('Invalid log in credentials, register?', category='danger')
        return redirect(url_for('login'))
    return render_template('app/login.html', form=form)


@app.route('/about', methods=['GET'])
def about():
    with open("./docs/README.md") as f:
        content = f.read()
    content = Markup(markdown.markdown(content))
    return render_template('app/about.html', content=content)


@app.route('/favicon.ico')
def fav():
    return send_from_directory(os.path.join(app.root_path, './static/img'), 'favicon.ico')

poptraq/templates/user/account.html
{% extends "layout.html" %}

{% block title %} Account {% endblock %}

{% block nav %}
    {% if current_user.is_authenticated %}
        <ul class="nav navbar-nav navbar-right">
            <p class="navbar-text">{{ current_user.email }}</p>
            <li><a href="{{ url_for('user.account')}}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
            <li><a href="{{ url_for('user.logout')}}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        </ul>
    {% else %}
        <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('user.register')}}"><span class="glyphicon glyphicon-user"></span> Register</a></li>
            <li><a href="{{ url_for('user.login')}}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        </ul>
    {% endif %}
{% endblock %}

{% block content %}

    {% with messages = get_flashed_messages(with_categories=true) %}
      <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissible text-center" role="alert" style="text-align: center;">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
              <!-- <strong>Title</strong> --> {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    <div class="container">
        <br/>
        <h2>Dashboard</h2>
    </div>
{% endblock %}

poptraq/templates/user/activate.html
<!doctype html>

<html lang="en">

<head>
    <meta charset="UTF-8">

    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Confirm Account</title>
</head>

<body>
<p>Welcome {{ name }}! Thanks for signing up. Please follow this link to activate your account:</p>

<br/>

<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>

<br>

<p>Cheers!</p>
<br>
<p><i>@poptraq</i></p>
</body>

</html>

poptraq/templates/user/details.html
{% extends "user/layout.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Details {% endblock %}

{% block nav %}
<ul class="nav navbar-nav navbar-right">
    <li><a href="{{ url_for('user.account')}}"><span class="glyphicon glyphicon-arrow-left"></span> Back</a></li>
    <p class="navbar-text"><strong>User Account:</strong> {{ current_user.email }}</p>
    <li><a href="{{ url_for('user.logout')}}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
</ul>
{% endblock %}

{% block content %}
<div class="container">
    <br/>
    <h2>Details</h2>

    <form class="form-horizontal col-sm-8" method="POST" enctype="multipart/form-data" action="{{ url_for('user.details')}}">
        {{ form.csrf_token }}
        {{ wtf.form_field(form.passport_photo) }}
        {{ wtf.form_field(form.age) }}
        {{ wtf.form_field(form.gender) }}
        {{ wtf.form_field(form.marital_status) }}
        {{ wtf.form_field(form.specifics) }}
        <input class="btn btn-success" type="submit" value="Submit"/>
    </form>
</div>
{% endblock %}

poptraq/templates/user/layout.html
<!DOCTYPE html>

<html>
<!--To change the CDNs and make them uniform-->
<head>
    <meta charset="UTF-8">

    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %} Poptraq {% endblock title %}</title>

    <!--favicon.ico img-->
    <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='img/favicon.ico') }}">

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!--User CSS-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/user.css') }}">

</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('index')}}">Poptraq</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="{{ url_for('about')}}">About</a></li>
        </ul>

        {% block nav %}
        <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('user.register')}}"><span class="glyphicon glyphicon-user"></span> Register</a></li>
            <li><a href="{{ url_for('login')}}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        </ul>
        {% endblock %}
    </div>
</nav>
<br/>
<br/>

{% with messages = get_flashed_messages(with_categories=true) %}
<!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }} alert-dismissible text-center" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <!-- <strong>Title</strong> --> {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

{% block content %}
<div class="container">
    <center>
        <h1>Poptraq - Population Analyser</h1>
        <h2>Current Statistics Data</h2>
    </center>
</div>
<br>
<div id="results">
    <table class="table table-hover table-striped table-responsive">
        <thead>
        <tr>
            <th>County ID</th>
            <th>County</th>
            <th>Sub-Counties</th>
            <th>Sectors</th>
            <th>Population</th>
            <th>Budget</th>
            <th>Size</th>
        </tr>
        </thead>

        {% for result in results%}
        <tr>
            <td>{{ result[0] }}</td>
            <td>{{ result[1] }}</td>
            <td>{{ result[2] }}</td>
            <td>{{ result[3] }}</td>
            <td>{{ result[4] }}</td>
            <td>{{ result[5] }}</td>
            <td>{{ result[6] }}</td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

<!--JQuery CDN-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!--Bootstrap JS-->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<!--User JS-->
<script src="{{ url_for('static', filename='js/user.js') }}"></script>

</body>

</html>

poptraq/templates/user/recover.html
{% extends "user/layout.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Recover Password {% endblock %}

{% block nav %}
<ul class="nav navbar-nav navbar-right">
    <li><a href="{{ url_for('user.register')}}"><span class="glyphicon glyphicon-user"></span> Register</a></li>
    <li><a href="{{ url_for('login')}}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
</ul>
<script src='https://www.google.com/recaptcha/api.js'></script>
{% endblock %}

{% block content %}
<div class="container">

    {% if reset %}
    <div class="container">
        <br/>
        <h2>Confirm Credentials user credentials to reset password</h2>
        <form class="form-horizontal col-sm-8" method="POST" action="{{ url_for('user.recover')}}">
            <dl>
                {{ form.csrf_token }}
                {{ wtf.form_field(form.email) }}
                {{ wtf.form_field(form.recaptcha) }}
            </dl>
            <input class="btn btn-success" type="submit" value="Submit"/>
        </form>
    </div>
    {% endif %}

    {% if new %}
    <div class="container">
        <br/>
        <h2>Set New Password</h2>
        <form class="form-horizontal col-sm-8" method="POST" action="{{ url_for('user.password_reset')}}">
            <dl>
                {{ form.csrf_token }}
                {{ wtf.form_field(form.password) }}
                {{ wtf.form_field(form.confirm_password) }}
                {{ wtf.form_field(form.recaptcha) }}
            </dl>
            <input class="btn btn-success" type="submit" value="Submit"/>
        </form>
    </div>
    {% endif %}

    {% if show %}
    <div class="container">
        <p>Dear user, a password reset link has been sent to your account. Please check your inbox (and your spam
            folder) -
            you should have received an email with a password link.</p>
        <br/><br/>
        <p>Didn't get the email? <a href="{{ url_for('user.recover') }}"><strong>Try again</strong></a>?</p>
    </div>
    {% endif %}

</div>
{% endblock %}

poptraq/templates/user/reset.html
<!doctype html>

<html lang="en">

<head>
    <meta charset="UTF-8">

    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Confirm Account</title>
</head>

<body>
<p>A password reset action has been activated. Please follow the link below to reset your password:</p>

<br/>

<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>

<br>

<p>Cheers!</p>
<br>
<p><i>@poptraq</i></p>
</body>

</html>

poptraq/templates/user/suspended.html
{% extends "user/layout.html" %}

{% block title %} Account {% endblock %}

{% block nav %}
{% if current_user.user and current_user.admin %}
    <ul class="nav navbar-nav navbar-left">
        <li><a href="{{ url_for('admin.home')}}"><span class="glyphicon glyphicon-refresh"></span> Switch</a></li>
    </ul>
{% endif %}
<ul class="nav navbar-nav navbar-right">
    <li><a href="{{ url_for('user.details')}}"><span class="glyphicon glyphicon-edit"></span> Details</a></li>
    <li><a href="{{ url_for('user.notifications')}}"><span class="glyphicon glyphicon-inbox"></span> Notifications</a></li>
    <li><a href="{{ url_for('user.settings')}}"><span class="glyphicon glyphicon-wrench"></span> Settings</a></li>
    <p class="navbar-text"><strong>User Account:</strong> {{ current_user.email }}</p>
    <li><a href="{{ url_for('user.logout')}}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
</ul>
{% endblock %}

{% block content %}

<div class="container">
    <br/>
    <h2>Dashboard</h2>
</div>
{% endblock %}

poptraq/templates/user/unconfirmed.html
{% extends "user/layout.html" %}

{% block nav %}
<ul class="nav navbar-nav navbar-right">
    <p class="navbar-text">{{ current_user.email }}</p>
    <li><a href="{{ url_for('user.unconfirmed')}}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
    <li><a href="{{ url_for('user.logout')}}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
</ul>
{% endblock %}

{% block content %}
<div class="container">
    <center>
        <h1>Welcome!</h1>
        <br/>
        <p>You have not confirmed your account. Please check your inbox (and your spam folder) -
            you should have received an email with a confirmation link.</p>
        <br/>
        <br/>
        <p>Didn't get the email? <a href="{{ url_for('user.send_confirm_link') }}"><strong>Resend</strong></a>?</p>
    </center>
</div>
{% endblock %}